### ISSUE TITLE
No compila la aplicación en strider

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-stopmotion#12]
Parece que hay un error en las dependencias, aparece el mensaje:

```
dpkg-gencontrol: warning: package huayra-stopmotion: unused substitution variable ${perl:Depends}
```

- http://ci.huayragnulinux.com.ar/huayralinux/huayra-stopmotion/job/57435700c6eddb224263a787

**Comment by iglosiggio** [comment]
El error parece salir de uno de los debhelpers (dh_perl) que probablemente quedó de alguna template vieja

http://man.he.net/man1/dh_perl
https://www.mankier.com/5/deb-substvars
http://man.he.net/man1/dpkg-shlibdeps
