### ISSUE TITLE
Probar la aplicación sobre OSX

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-stopmotion#16]
La aplicación está diseñada para mostrar un fallback en caso de usarse en un sistema no linux, como osx.

**Comment by hugoruscitti** [comment]
Arroja un error, aparentemente faltan algunas imágenes:

![developer tools 2016-11-05 21-06-45](https://cloud.githubusercontent.com/assets/99183/20034399/cab36dec-a39b-11e6-9217-1cd396e04353.png)

De todas formas, creando unos archivos .png con esos nombres, para eludir ese error, la aplicación parece iniciar bien e imprime el mensaje: "No se pudieron cargar v4l2 y/o udev" y en la interfaz el botón de cámara indica: "Sin cámara (no hay cámara seleccionada)".

Salvo el detalle de las imágenes que faltan, lo demás parece funcionar bien. ¿es lo esperado no?, ¿o el fallback esperado es otro?

**Comment by iglosiggio** [comment]
Es lo esperado, me parece que me olvidé de commitear esas imágenes, el
lunes lo vemos!

**Comment by hugoruscitti** [comment]
Ahhhh, genial. Entonces anda bien :)

por cierto, recién me doy cuenta que en el archivo .gitignore está la regla "*.png", por eso pasó pasaron desapercibidas las imágenes me parece... 

https://github.com/HuayraLinux/huayra-stopmotion/blob/basic-webcam/.gitignore#L20

cierro el issue, lo quería anotar acá para no olvidarme en la semana.
