### ISSUE TITLE
Save fails when /tmp is mounted on different partition

### ISSUE THREAD

**Issue by lingo** [HuayraLinux/huayra-stopmotion#2]
I'll attach a patch to fix this soon.  

This occurs in src/js/servicios/proyecto.js, in `mover_imagenes`

fs.renameSync fails with ENONENT

Añadiré un patch para reparar este problema.  Ese ocurre en linux cuando '/tmp' está montado en una partición distinta a la donde se guarda el proyecto.
Falla `fs.renameSync` con el código error **ENOENT**

**Comment by iglosiggio** [comment]
Estamos reescribiendo la aplicación, voy a cerrar el issue, te pido disculpas personales por no haberlo respondido nunca!
