### ISSUE TITLE
Incompatibilidad con Debian 10

### ISSUE THREAD

**Issue by quirinux-so** [HuayraLinux/huayra-stopmotion#21]
Como director del proyecto **Quirinux**, un sistema operativo hecho para el cine de animación, me interesa mucho incluír esta aplicación excelente. En verdad los felicito.

La próxima versión de Quirinux estará basada en **Debian 10** y muchas cosas cambiaron desde **Debian 8**. No he logrado solucionar la dependencia **node-webkit**. 

Cualquier ayuda que pudieran aportarme al respecto, estaría más que agradecido. 

Charlie Martínez
cmartinez@quirinux.org

**Comment by iglosiggio** [comment]
Hola! soy ex-dev de huayra. node-webkit no es una dep que estuvo disponible en debian nunca (al igual que electron). Cómo es un runtime que cada aplicación usa la versión que le sirve no tiene mucho sentido empaquetarla en una distribución como debian (en nuestro caso manteníamos todo nuestro sw en la misma versión del runtime).

Lo más viable sería mudar la versión estable a electron y que ustedes empaqueten todo bundleado o que mantengan un paquete de electron. Otra posibilidad es usar flatpak, que mantiene electron como runtime versionado.

Tengo tiempo limitado para colaborar pero puedo dar direcciones xq masomenos recuerdo cómo estaba hecho el proyecto.

**Comment by quirinux-so** [comment]
Hola Ignacio!

Qué alegría que me escribas, en verdad te lo agradezco mucho! 

Soy un desarrollador bastante limitado, a decir verdad por ahora sólo
programo GUI en Gambas3 para ejecutar scripts de bash... Quirinux es un
trabajo similar al de AV Linux, incluso está hecho con Systemback. Pero
está teniendo cierta repercusión, y con la ayuda de gente como Javier
Obregón de Etertics / GobMis, y Gustav de Tupi, estoy logrando recopilar
programas muy interesantes. 

En verdad me encantaría incorporar Huayra - Stopmotion, porque posee
algo que no encontré en ninguna otra herramienta libre similar: la
posibilidad de dibujar guías sobre la pantalla. Eso y una x-sheet
vertical son funciones muy pedidas, pero mientras que aquella ya
fueincluida en Tupi y OpenToonz, el dibujo de guías no. 

Ahí estoy viendo un poco de que se trata electron. ¿Tu que opinas? ¿Qué
ocupara menos espacio? ¿migrarlo a electron o a flatpak? Te lo pregunto
porque en verdad desistí incluir en la imagen de Quirinux software
proveniente de snap y flatpak porque el peso de la imagen terminaba
excediendo los 4 GB (Quirinux trae bastantes cosas). En tal sentido, lo
que mejor resultado me dio fueron las .appimage 

Desde ya que hoy por hoy no sé hacerlo bajo ningún sistema, pero me
pongo a estudiar de inmediato lo que me digas y ejecuto los comandos que
me pases, cuando tengas tiempo para enseñarme todo eso claro. Sin
compromiso y sin apuro. 

Sigamos en contacto por favor! 
Un saludo, 
Charlie 
:-)

**Comment by iglosiggio** [comment]
Con appimage no tengo experiencia y supongo que podría complicarse un poco (aunque no estoy seguro).

De buenas a primeras empaquetar con electron si no importa tener todo híper ordenado es masomenos fácil, cuando tenga un rato libre me voy a armar una lista de que cambios se deberían hacer acá y lo discutimos en el grupo de tg de huayra.

Flatpak lo que permite es tener un paquete fácil de instalar en cualquier distro, pero estos paquetes terminan pesando __bastante__, lo cuál puede generarte un dolor de cabeza.

Lo miro en unas horas y te comento cuando pueda si es mucho laburo (espero que no).

**Comment by quirinux-so** [comment]
Qué grande !!
 Sí, por lo que me dices y por lo que voy chusmeando lo de electron
sería lo más viable. 
 Cuenta conmigo para hacer las cosas que requieran más tiempo, siempre
que más o menos me puedas orientar.
 Me da mucha alegría.
 Un saludo!
 Charlie

**Comment by iglosiggio** [comment]
Arranqué el proceso de portar a electron, estoy tocando la codebase lo menos posible xq no la conozco lo suficiente (yo laburé en la versión que nunca salió).

![Estado actual del port a electron](https://user-images.githubusercontent.com/1154680/76869679-6a15c600-6847-11ea-85b3-fd37b7bedeb7.png)

Si logro tener los menús andando (lo último de "adaptar a electron que me queda") me fijo de armar un .tar.gz binario fácil de correr y te lo paso para que lo pruebes a fondo.

**Comment by iglosiggio** [comment]
Logré tener funcionando casi todo excepto el compartir cámaras (porque en navegadores modernos requiere que la página hosteada sea https). Dejo mis cambios en [iglosiggio/huayra-stopmotion](github.com/iglosiggio/huayra-stopmotion)

**Comment by matiasdelellis** [comment]
Groso Nachin!!
Abrazo!.

**Comment by malefico3d** [comment]
buenaaaaa

**Comment by quirinux-so** [comment]
GENIOS !!!
Por acá sigo retocando detalles a los asistentes que tendrá Quirinux 2. 
Seguimos en contacto,
y MILES DE GRACIAS,
Charlie

**Comment by quirinux-so** [comment]
Ah, me gustaría comentarles que quien me habló de este programa fue el dibujante y animador **Gustavo Deveze**. 
Yo ya había probado **Huayra** hace unos años, pero creo que la versión 1 y no sé si estaba ahí, porque no lo recordaba. 
En verdad es una maravilla, gracias por revivirlo.
:-)

**Comment by malefico3d** [comment]
Gustavo es un amigazo! Lo conocí hace unos años cuando estabamos metiendo
Tupi en Huayra y quedamos amigos.

Saludos!

**Comment by quirinux-so** [comment]
Hola cómo están?

Ví que salió la versión 5.0 de Huayra, aún no pude descargarla. Y me surgió la duda: ¿incluye este programa? Porque de ser así, entiendo ya habrán logrado pasarlo a electron. Sigue interesándome su inclusión en Quirinux.

Un saludo

**Comment by alvarezgarcia** [comment]
Buenas, qué tal?

Sí, Huayra 5 incluye huayra-motion. Sin embargo aún no tenemos una versión funcional para Electron, estamos trabajando en ella haciendo algunos cambios que vamos a ir publicando por acá.

Gracias!

**Comment by quirinux-so** [comment]
Genial!! Siendo que Huayra 5 está basada en Debian 10, es probable que la versión que han incorporado funcione en Quirinux. Les ruego me avisen si la empaquetaron en .deb o si actualizaron las instrucciones para compilarla, ya que es una gran herramienta. Felicitaciones por el lanzamiento, me alegró mucho. Un saludo

**Comment by ftoledo** [comment]
Hola @quirinux-so el .deb actual te tiene que funcionar sobre debian 10, pero tambien tenes que instalar el .deb de node-webkit que tenemos. Ya que depende de el.

http://repo-huayra.conectarigualdad.gob.ar/huayra/pool/non-free/n/node-webkit/
http://repo-huayra.conectarigualdad.gob.ar/huayra/pool/main/h/huayra-stopmotion/

**Comment by quirinux-so** [comment]
> 
> 
> Hola @quirinux-so el .deb actual te tiene que funcionar sobre debian 10, pero tambien tenes que instalar el .deb de node-webkit que tenemos. Ya que depende de el.
> 
> http://repo-huayra.conectarigualdad.gob.ar/huayra/pool/non-free/n/node-webkit/
> http://repo-huayra.conectarigualdad.gob.ar/huayra/pool/main/h/huayra-stopmotion/

Maravilloso, muchas gracias por los enlaces. Un saludo.

**Comment by quirinux-so** [comment]
Efectivamente, huayra-stopmotion funciona muy bien en Debian Buster. Solucionada la incompatibilidad, pienso que corresponde cerrar este hilo. Estaré atento a todos los avances de este programa. Un saludo

**Comment by ftoledo** [comment]
Excelente @quirinux-so , cualquier cosa que encuentres abrinos un ticket.
Esperamos poder migrarla completo a electron y modernizarla.
Abrazo!

**Comment by quirinux-so** [comment]
Hola! Me gustaría compartirles un .deb que de huarya-motion que acabo de hacer para Quirinux. Sirve para Debian Buster y la única diferencia con el oficial es que este viene con el node-webkit incluido:

http://my.opendesktop.org/s/doRGs6kHscxbfng
