### ISSUE TITLE
dependencia de ffmpeg

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-stopmotion#3]
Para tener en cuenta, ffmpeg ya no está en debian sino que es reemplazado por libav
El comando avconv reemplaza al comando ffmpeg (calculo que funcionaria igual para stopmotion) y esta en el paquete libav-tools

Calculo que para mantener compatibilidad con wheezy y jessie (base de Huayra 3.0) podemos poner como dependencia:

```
Depends: node-webkit, ffmpeg | libav-tools (>= 6:10.2-1), uvcdynctrl, uvccapture
```

Luego comprobar si existe /usr/bin/ffmpeg o /usr/bin/avconv para elegir que ejecutable usar.

**Comment by iglosiggio** [comment]
Cierro porque la versión nueva usa mlt :P
