### ISSUE TITLE
abrir un archivo asociado a la aplicación

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-stopmotion#6]
La aplicación debe abrir los archivos de proyectos asociados a la extensión **.hmotion**.

**Comment by hugoruscitti** [comment]
Por lo que ví en huayra 3 está solucionado, lo marco como "cerrado"

**Comment by ftoledo** [comment]
Lo que está funcionando es la asociación, pero la aplicación no abre el archivo de proyecto que recibe como parámetro.

**Comment by ftoledo** [comment]
En la 0.5.1 ya está solucionado
