### ISSUE TITLE
Error al guardar proyectos en directorios con espacios

### ISSUE THREAD

**Issue by hugoruscitti** [HuayraLinux/huayra-stopmotion#7]
Eso, parece que la aplicación falla cuando intenta guardar un proyecto
en un directorio que tiene espacios en el nombre.

**Comment by nachopro** [comment]
Se hicieron pruebas en la versión 0.4.17 y no pude reproducir el error.
¿Lo cerramos @hugoruscitti?

**Comment by hugoruscitti** [comment]
Buenisimo, dales, lo cierro.
